### ISSUE TITLE
Send Sub-WG Kick Off Package

### ISSUE THREAD

**Issue by ChristineP2024** [PHACDataHub/irg#18]
The following is the documentation to send to Sub-WG members prior to the meeting. 

Note: this card will cycle through as we will send documentation on a biweekly basis. 

Package includes:
- ToR
- Agenda
- Deck
- Call for Documentation including list
```[tasklist]
### Tasks
- [ ] Henry to review agenda and deck
- [x] Michelle to confirm the list of documentation
- [ ] Andrew to coordinate sending the package with Frida
```
