### ISSUE TITLE
Confirm Sub-WG Membership List - IDVPB rep still O/S

### ISSUE THREAD

**Issue by samiatoui** [PHACDataHub/irg#4]
Prior to launching the Sub-WG, need to confirm the members. This will make up the email distribution list. It will also determine who gets the link to the GitHub doc repository. 
```[tasklist]
### Tasks
- [x] Henry to confirm IDVPB rep with IDVPB
- [x] Send an email to DHTD to confirm Sub-WG member
- [x] Add Seb as a member
- [x] Add CIHI as a member
- [x] Confirm completeness of membership list
- [x] Add Nicolas Gilbert to the membership list as rep from IDVPB
```

**Comment by ChristineP2024** [comment]
As of Oct. 1, IDVPB rep pending. Henry is following up (see emails)
