### ISSUE TITLE
Prep Sub WG Meeting 3

### ISSUE THREAD

**Issue by ChristineP2024** [PHACDataHub/irg#47]
The Sub WG meetings every 2 weeks; 2nd meeting is on Oct. 17th. Prep includes:

Main topic: The PoC
Meeting material includes
Agenda
Deck
Additional docs (TBC)
```[tasklist]
### Tasks
- [x] Confirm Approach
- [x] Prep the agenda
- [x] Prep the deck
- [x] Prep additional docs
- [x] Send to Henry for review
- [x] Sami to upload in Git Hub
- [x] Christine to prep the email and send to Frida
```
