### ISSUE TITLE
Prep for Sub WG Meeting 4

### ISSUE THREAD

**Issue by ChristineP2024** [PHACDataHub/irg#53]
The Sub WG meetings every 2 weeks; 2nd meeting is on Oct. 17th. Prep includes:

Main topic: What We Heard
Meeting material includes
[[Agenda](https://022gc.sharepoint.com/:w:/r/sites/ProjectImmunizationRecordGatewayDSFB-SDPI/Shared%20Documents/Product%20Team/Sub-Working%20Group/Meetings/4%20-%20Nov%2014%202024/Federated%20Data%20Pilot%20Sub-WG%20Meeting%20Agenda%20November%2014%202024.docx?d=w90c44d64f5fc49229bd301330b1751ac&csf=1&web=1&e=5SbQVX)]
[Deck](https://022gc.sharepoint.com/:p:/r/sites/ProjectImmunizationRecordGatewayDSFB-SDPI/Shared%20Documents/Product%20Team/Sub-Working%20Group/Meetings/4%20-%20Nov%2014%202024/Federated%20Data%20Pilot%20Sub-WG%20November%2014%202024.pptx?d=w5aa59f07f4f5414fbbbb5e2f0728e86a&csf=1&web=1&e=Phk7W5)
Additional docs (TBC)
```[tasklist]
### Tasks
- [x] Confirm approach
- [x] Prep agenda and deck
- [x] Prep additional material if required
- [x] Hold review session
- [ ] Sami to upload documents in Git Hub
- [ ] Prep email for Sub WG members and send to Frida for distribution
```

**Comment by ChristineP2024** [comment]
I've created the first drafts of the agenda and deck. Michelle to develop the slides providing a summary of information gathered to date.
